### ISSUE TITLE
我希望了解一个问答网上受关注最多的问题是哪些

### ISSUE THREAD

**Issue by pimgeek** [mindpin/problems#12]
### 下图中被标注的部分, 就是问题的受关注总数

![image](https://cloud.githubusercontent.com/assets/1609306/2533872/612b68e6-b56b-11e3-9511-7cb96994ee70.png)

目前,我在网上只能看到与用户相关的数据统计, 我很想知道能否了解到与问题相关的数据统计, 我最关心的就是被关注数.

http://www.funnyjs.com/zhihudata/topuser/

**Comment by ben7th** [comment]
“一个问答网站”就是知乎呗

在知乎的网站上点“发现”，里面有个今日最热和本月最热。
我不太清楚他这个“最热”是根据什么指标来排，可能回答数，关注数都涉及到了。

虽然这个“最热”榜和你需要的关注数排行有一些差别，但不知道是否能达到目的？
或者说你想要的对关注数的统计不止是最热排行，而是其他的统计？比如分布？
能否进一步把想要的说明，我可以考虑如何去低成本的做。

**Comment by pimgeek** [comment]
我的根本目的, 就是试图以最小的答题成本, 获取最大限度的点赞和关注. (相当于吸引注意力) 

今日最热与本月最热, 可能是一个经常变化的值, 我不确定能否实现我的目的. 

但我的想法也不一定对: 【如果一个问题的关注人数超过了一定阈值, 比如大于 10000 , 这个问题从长远来说给我带来的赞也会更多.】

对此你有什么见解？

**Comment by ben7th** [comment]
我看了
http://www.funnyjs.com/zhihudata/topuser/
这个的统计

它里面包含的指标很多，包括一些变化率的计算。
这是远比排行榜复杂和有用的。

你的意思是否是以问题关注为核心来进行类似指标的统计？
我其实是正在想较低成本的数据获取方法。目前有后台蜘蛛抓取和前端浏览器插件获取两种思路。

**Comment by ben7th** [comment]
计划基于网页 javascript 脚本在 console 里运行的方式来获取统计信息。
已加入执行队列。

最新执行队列情况：
http://s.4ye.me/ttuFmH

**Comment by ben7th** [comment]
@kaid 正在尝试做这个，可以参考
http://www.funnyjs.com/zhihu_ranking_0_2/#more-26

**Comment by kaid** [comment]
已经初步完成了一个脚本https://gist.github.com/kaid/9931456

**现在的问题是:**
1. 在初始载入最多49个(`知乎的限制，当月最热最多只能载入49个项目`)问题后，需要较长时间去解析所有种子问题的关注者并筛选他们活动信息里的问题相关项目(`因为有的问题关注者较多，总数加起来可能有数万的关注者`)。
2. 界面仍然比较简单，需要再多些优化。比如长时间没有更新的时候，会让人以为执行完毕。

**Comment by ben7th** [comment]
已经试用，很实用~~ 先做到这里，用一用再提新需求~~
