### ISSUE TITLE
我需要一种可根据关键词做筛选的自动完成工具

### ISSUE THREAD

**Issue by pimgeek** [mindpin/problems#16]
#### 上文场景
- 我经常需要输入一行字到电脑里. 这行字的作用是 **[每当我看到这行字, 就能想起一件特定的事. 不看的时候, 我就是想不起来]** 
- 在很多情况下, 我都是在与别人谈论事情的时候, 或者自己手头上有一个任务的时候, 才想到要记录这行字的, 所以, 我希望很快输入到电脑里. 例如: 我在讨论大量创造网站内容的问题, 或者在处理大批量内容录入相关的任务, 被数据不规范的问题困扰着, 才会想到 **[众包]**. 
#### 下文场景
- 我需要回想起一件事, 这件事大概与 **[众包]** 有关系, 但具体是什么事, 我得看过当初写下的一句话才能回想起来.
- 在很多情况下, 我都是在与别人再次谈论某件事, 或者需要提一个直接涉及众包的开发需求的时候, 只要让我看到 **[含有众包这个关键词的所有句子]**, 我就能回想起来, 并且立刻加入开发需求中.
#### 输入说明

我需要有一个编辑框, 在这个编辑框中, 我可以输入一些简单的关键词, 比如 **[众包]**
#### 关键处理过程

程序在预先存储好的列表中过滤出所有与 **[众包]** 相关的句子, 并且完整地排列出来
#### 界面参考

![image](https://cloud.githubusercontent.com/assets/1609306/2557625/0f26a19a-b710-11e3-861f-8f821fd902e9.png)

**Comment by ben7th** [comment]
你期望的这个东西的数据来源是什么捏？

**Comment by pimgeek** [comment]
数据的来源, 是我们团队里任何人创造的笔记片段, 一般是一张图配合相关的讲解文字. 这样的 [笔记片段]

1 可以被串接成 Oppia 教程, 虽然目前还不能直接整合进 Oppia, 但可以作为素材收集.
2 可以被串联进入 [目标逐层分解的网络]. 这样的笔记片段, 我的 Zim 笔记本里已经有很多了.

我举一个例子, 你看看是否对理解有帮助?

![image](https://cloud.githubusercontent.com/assets/1609306/2601404/33987564-bb0f-11e3-8e9f-eb57f13d1d8e.png)

**Comment by ben7th** [comment]
我的意思是，数据来源是哪个服务，或者哪个软件，不是说人

**Comment by pimgeek** [comment]
如果要往软件/服务方面说, 那么我想 [github 的 gist], 我们团队正在开发的 [团队私密笔记], 包括 [老导图站上的 思维导图] 都可算做软件层面的数据来源吧. 这样想会不会有问题?

**Comment by ben7th** [comment]
数据来源需要两个条件

1 结构化
2 大家都习惯往上面积累

所以现在的问题并不是做不做筛选工具的问题

而是目前不存在这样一个数据来源

**Comment by pimgeek** [comment]
1 这个问题我也考虑过了, 刚刚举出的三个数据源, 都属于访问 URL 相对有结构的, 而且我也可以要求初期只要把标题拿来做索引就可以.

2 要想很多使用者都 [有积累的习惯], 先有工具才可以谈, 而不是先有习惯后有工具. 

换个角度看要求 2 : 你是不是想说, 我需要再认真想想, 最好能把某个 [已经形成积累习惯] 的 [结构化输入流] 引导到我们的入口上来? (而不是假设 -- 一旦架设好一个很有趣的工具, 那么会有人自动过来输入?)

**Comment by ben7th** [comment]
是的，由于每个问题需要解耦的看，我需要在解决这个问题时，以已经存在的基础设施为条件。

另外，确实是先有工具才能有习惯，那就需要先找或者先开发笔记工具，而不是“基于笔记工具的”筛选工具

**Comment by pimgeek** [comment]
我理解你的意思了, 这个地方是我有思维跳跃, 我把自己已经形成的 [记录结构化笔记习惯] 当成是大家都有(或者很快就有)的习惯 --- 这是信念, 不是事实.

针对 [另外] 这一点, 我提一些新的 Problems, 把结构化笔记的 [期望结构] 和 [期望操作方法] 描述出来 (尽量剥离我自己的解决方案).

**Comment by ben7th** [comment]
好。
另外如果你把你目前的笔记工具作为基础设施，希望为它开发插件，或许也可以作为问题单独提出。让我们这边进一步评估可执行性（我们调研前并不熟悉你的笔记工具的数据结构）

**Comment by ben7th** [comment]
这个问题先close了。
