### ISSUE TITLE
需要一个key/value存储服务

### ISSUE THREAD

**Issue by ben7th** [mindpin/problems#18]
一些浏览器增强功能的开发可以用这种服务来做存储。
服务以web服务形式提供，能够把指定的value值存入指定的key，并读取出来。
可以自己开发或者寻找现成的服务。

**Comment by ben7th** [comment]
这个服务应该用于支持一些浏览器插件开发。可以通过JSONP的方式远程调用。
参考：http://www.cnblogs.com/dowinning/archive/2012/04/19/json-jsonp-jquery.html

不过一开始先做好服务端设计即可。

**Comment by ben7th** [comment]
已经加入执行队列：
http://s.4ye.me/ttuFmH

执行方法：
http://s.4ye.me/QPrUv7

**Comment by kaid** [comment]
已经push到https://github.com/kaid/kv_service

**Comment by ben7th** [comment]
OKOK
