### ISSUE TITLE
需要某种存储或采集机制，来存储全局性的团队日志、素材库

### ISSUE THREAD

**Issue by advancer-zz** [mindpin/problems#19]
下面这段文字，或图片，作为个人的感想、素材库，并想直接分享到团队内部：
（1）我不想发到具体的项目或问题中，干扰具体的项目；
（2）我不想发邮件，不便于今后的积累与反思；
（3）我想作为某种记录，今后可被团队或外面的人看到；
（4）我想在写某些文章或组织思路时，能搜索到这些内容，抽取出来后，重新修改、组织后再利用，形成新的文章，推送给他人；

比如，下面这段文字：
关于中国技术型创业思路的思考，刚才突然有种想法，我们国内的技术人员，若要创业，可能还需要重点关注在“实用新型”上，即重点解决某部分用户实际、具体的问题，以务实为优先，在确保先解决好许多实际小问题的基础上，再来考虑长远的、大的解决方案，或者所谓的理论性的、框架性的、战略性的东西。原因或许也很简单，初期我们不具备足够的资源、执行能力，甚至也缺乏足够的耐心，来考虑长远的、可行的解决方案。
或许，从可操作性来说，只有先学会解决那些简单的、短期的问题，才有资格、能力来解决那些复杂的中长期问题吧...

**Comment by ben7th** [comment]
我觉得可以用wordpress架设一个内部blog来分享这些文章段落性质的东西。

**Comment by ben7th** [comment]
或者 LOFTER 这样的轻博客系统，我目前直觉上能字面上满足
（1）（2）（3）（4）
但肯定每条都和期望中的具体特性有差异

是否可以把具体特性差异的地方作为更小的问题剥离出来。

**Comment by pimgeek** [comment]
我也很关注这 (1) (2) (3) (4) 四个要点, 我目前的手工解决方法, 只能解决部分问题, 我还在试图写出更精确的功能描述, 把 [我的痛点] 转化为 [可执行的 problems].

对于 (1),  我也不会随时打断大家, 要求他们都来关注我的关注焦点: 我希望当人们自己意识到 [自己的创业心态有点浮躁时] 就会在别人的指引下, 很快看到 [如何克制浮躁心态这个目标] 及其[解决步骤]. 如果人们在认真地忙手头的事情, 他们完全无需看到 [克制浮躁心态这个目标及其解决步骤].

对于 (2) , 我不会只发邮件, 而是先用我的 yEd 绘图工具写下来, 再发送截图, 自己保留源文件

对于 (3) , 我即将提新的 problems ... 暂时不提.

对于 (4), 我想用前几天给你们展示的那个 [目标逐层分解模型] 来存储, 以便未来容易 [抽取] [修改] [组织] [再利用], 如下图所示.

![image](https://cloud.githubusercontent.com/assets/1609306/2611598/35969e10-bba8-11e3-86c7-9a212b905814.png)

**Comment by advancer-zz** [comment]
我想，可能（4）再组织与组合可能是此较模糊不定的了。对于这一条，能否做到将关键词所属的，关联到的段落排列形成列表后直接插入新文章做为参考资料或素材。一般若是网络上的杂文这样做可能有很大噪音，但自己或团队的观点，由于其往往具备大致差异不大的模式，相对噪音低些，可行性高些。

**Comment by pimgeek** [comment]
你对 (4) 的进一步描述, 我只能了解到大概目的, 无法理解到具体操作是怎么做的. 如果你能给出一张图, 里面有这些可操作实体:

a [关键词]
b [关键词所关联的段落]
c [这些段落被插入新文章后, 呈现出来的效果]

那么我会理解得更清楚一些. 

我给出的示意图, 就有对应的可操作实体

i [两篇原始文章结构 (点网)]
ii [一堆无结构的段落 (圆点)] 
iii [把绿色段落重组之后, 呈现出来的效果 (点网)]

**Comment by advancer-zz** [comment]
我想，在初始阶段，可以更简化到，先利用a [关键词]，将团队中自己和他人的b [关键词所关联的段落]串起来，形成简化的c 列表。
然后再来考虑改进...

**Comment by advancer-zz** [comment]
建议，在关闭该问题后，输入类型的子问题优先考虑，或许先确保有足够的输入后，后面的应用才容易有具体的易操作思路...

**Comment by ben7th** [comment]
经过周末的电话讨论，这个problem将被拆分成几个更容易单独执行的problems

**Comment by pimgeek** [comment]
@advancer 我完全同意. 请参考 #20 #21 , 这两个 problem 都是针对输入来说的.
