### ISSUE TITLE
需要一个内部图文分享的 blog 系统

### ISSUE THREAD

**Issue by ben7th** [mindpin/problems#25]
此需求衍生自 https://github.com/mindpin/problems/issues/19

需要部署一个blog系统，满足以下需要：
1. 支持使用MINDPIN账号登录
2. 支持富文本编辑录入
3. 支持上传图片到 img.4ye.me 服务。并支持输入框内粘贴上传。

**Comment by ben7th** [comment]
已经加入执行队列：
http://s.4ye.me/ttuFmH

**Comment by ben7th** [comment]
在publify的源代码基础上，进行以下修改：
1. 用户验证改为使用 MINDPIN HTTP 用户验证进行远程验证。验证通过时把用户信息读到本地数据库；
2. 富文本编辑器使用 http://ckeditor.com/ CK编辑器
3. 图片上传服务的前后端整合届时可以和我细化讨论。

**Comment by kaid** [comment]
**对于ckeditor插件simpleuploads的修改:**
1. [form输入框名](https://github.com/kaid/publify/blob/master/app/assets/javascripts/ckeditor/plugins/simpleuploads/plugin.js#L212)
2. [ajax上传formData参数名](https://github.com/kaid/publify/blob/master/app/assets/javascripts/ckeditor/plugins/simpleuploads/plugin.js#L1872)
3. [ajax返回解析](https://github.com/kaid/publify/blob/master/app/assets/javascripts/ckeditor/plugins/simpleuploads/plugin.js#L1661-L1672)

**对publify用户系统的修改:**
1. 删除了`app/controllers/accounts_controller.rb`里的注册以及密码找回的相关代码:
   - [注册相关](https://github.com/kaid/publify/commit/c4401a1885484c62186227fd9b0db2a113dcdbef#diff-1bc3ab831747b674bed38478e5269232L26)
   - [密码找回相关](https://github.com/kaid/publify/commit/c4401a1885484c62186227fd9b0db2a113dcdbef#diff-1bc3ab831747b674bed38478e5269232L48)
2. User模型上重新实现了用户验证方法，删除了密码相关的代码:
   - [用户验证](https://github.com/kaid/publify/commit/c4401a1885484c62186227fd9b0db2a113dcdbef#diff-4676c008b11a5480d73d4a6de01e45b9L68)
   - [密码相关](https://github.com/kaid/publify/commit/c4401a1885484c62186227fd9b0db2a113dcdbef#diff-4676c008b11a5480d73d4a6de01e45b9L145)
3. 修改了博客初始管理员用户的注册流程:
   - [初始管理员注册](https://github.com/kaid/publify/commit/c4401a1885484c62186227fd9b0db2a113dcdbef#diff-96d7538446a97258fe291a027a04c6baL11)
4. 修改了用户头像的获取方法:
   - [用户头像](https://github.com/kaid/publify/commit/c4401a1885484c62186227fd9b0db2a113dcdbef#diff-127a850b7d7b20173ad3fba88f8a25e3L109)
