### ISSUE TITLE
架设一个网页收藏服务

### ISSUE THREAD

**Issue by ben7th** [mindpin/problems#26]
该服务提供web API，便于收藏网页。

该web服务接收传入的 网页URL，标题，描述信息，TAGs，生成收藏记录。

该工作衍生自 https://github.com/mindpin/problems/issues/23
并将作为 https://github.com/mindpin/problems/issues/21 的基础依赖之一

**Comment by ben7th** [comment]
已经加入执行队列：
http://s.4ye.me/ttuFmH

**Comment by ben7th** [comment]
已经部署到：http://collect.4ye.me/
下面由 @ben7th 进行前端开发

**Comment by kaid** [comment]
已经迁移到rails 4.1, 分支`feature/migrate_to_rails`, @ben7th @fushang318 测试下，没问题的话就合并到develop
