### ISSUE TITLE
支持贴图的 markdown 语法编辑器

### ISSUE THREAD

**Issue by ben7th** [mindpin/problems#29]
团队工作中经常撰写 markdown 语法格式文本。目前在 docs.4ye.me 添加的文本信息亦遵循 markdown 语法标准。

目前需要一个相对来说更好用一些的 markdown 语法文本编辑器。
考虑用 ACE Editor 来作为基础，添加一些自己想要的功能特性。

做好后先作为功能特性来替换 docs.4ye.me 的编辑器。

**Comment by ben7th** [comment]
加入任务执行队列：http://s.4ye.me/ttuFmH

**Comment by kaid** [comment]
已完成https://github.com/kaid/mde-4ye
