### ISSUE TITLE
我需要一个类似-fengcheco.com-的任务编辑器那样的输入界面

### ISSUE THREAD

**Issue by pimgeek** [mindpin/problems#30]
# 问题描述

我在试图手动录入大量有标题和文字说明的文本内容录入到 fengcheco.com 时, 使用了它的 Web 任务编辑器界面. 我希望把这个界面的部分 feature 借鉴过来为我所用.
# 参考链接和截图
- fengcheco.com 的 Web 任务编辑器, 需要注册登录才能使用

登录后, 找到类似下图这样的界面, 这就是我所谓的 Web 任务编辑器.
![image](https://cloud.githubusercontent.com/assets/1609306/2752106/07940ea8-c8ff-11e3-81b7-7cb5b2b44085.png)
# 主要 feature 要求:

1 点击标题就可以编辑标题, 离开编辑框就自动保存
2 点击内容就可以编辑内容, 离开编辑框就自动保存

**Comment by ben7th** [comment]
这就是 inplaceedit，一种很常见的输入体验形式。
这个形式用在什么地方呢？

就好像，“我希望生活中多一些绿色”。但是绿色是刷在墙上呢，还是绿色的衣服呢，还是绿色的地板呢，还是绿色的家具呢？

这是一个很小的 feature，不针对任何特定问题。MINDPIN导图编辑器的每个节点编辑就是用的这种体验。所在的上下文比它做到的还要复杂很多。也就是说这并不是一个很高深的体验，很容易做到。也随时可以用在任何你希望用在的地方。

![image](http://mindpin.oss-cn-hangzhou.aliyuncs.com/image_service/images/Ha29oe7e/Ha29oe7e.png)

而单独提这个体验的话，我没有地方可以承载它。也就是说把体验本身作为 problem 的话，这个 problem 无法 get done 和验收。

problem 列表的核心思想还是针对问题的。把体验单独提出可以作为对我的提醒，但是没有办法产生任何执行和派出任何任务。

如果目前或将来，在我们自己的产品中任何地方可以有应用这个体验的地方，你可以告诉我希望用在哪里。而目前缺乏上下文的 feature 无法产生任何实际执行。 我 close 掉它。

**Comment by ben7th** [comment]
换言之，你提的问题在我看来并不是一个问题。

“把这个体验借来为我所用”，就好像“寄几根X射线来让我检查身体”……一样。。

你得告诉我，希望用在哪里，希望改善你现在手头正在用的什么工具。

**Comment by pimgeek** [comment]
好的, 非常感谢, 至少我得到了两项信息.
1. 这个输入体验在其它涉及输入和编辑的地方也有, 且在补足上下文后有可能在短时间内实现.
2. 以后我自己觉得与此相似的体验层面的需求, 可以跳过 problems 描述, 通过聊天工具问你 [这种体验是否适合提 problem?]

**Comment by ben7th** [comment]
可以，体验层面的素材（需要借鉴的操作形式，动画形式，输入形式）也是需要积累的。
很多体验效果可能在我看来也是比较新颖的。
但是目前来看他不宜和 issues 混淆。目前我这里在个人层面上有所积累，但是远远不够规范。如果我总结出比较规范化的体验描述方法的话，我会想办法建立体验素材数据库，将来也许能以某种方式开放给整个团队。
