### ISSUE TITLE
直接从网页内容获取截图

### ISSUE THREAD

**Issue by ben7th** [mindpin/problems#34]
花瓣网的chrome插件，能够从网页以框选的形式获取某个区域的base64编码，并保存到服务器。

需要调研一下这个机制在chrome上是如何做到的。

截图示意：

![](http://mindpin.oss-cn-hangzhou.aliyuncs.com/image_service/images/s0FAKFrY/s0FAKFrY.png)

![](http://mindpin.oss-cn-hangzhou.aliyuncs.com/image_service/images/Dvsn6he4/Dvsn6he4.png)

花瓣网 chrome 采集工具安装：
http://huaban.com/about/

**Comment by kaid** [comment]
有两种思路解决:
1. **w3c标准javascript API**:
   利用[html2canvas](http://html2canvas.hertzen.com)库来渲染当前网页的一部分至canvas内然后导出canvas到图片.
   
   **缺点**: 无法截取flash、java applet等浏览器插件内容以及非同源iframe内容.
2. **Chrome插件API**:
   利用Chrome的平台API请求当前标签页内的图形缓冲区信息, 获取base64编码的data-url, 并在此基础上做进一步处理(裁切、标注等等).
   
   **缺点**: 依赖Chrome平台

参考资料:
- [Test Screenshot Extension官方样例](https://developer.chrome.com/extensions/examples/api/tabs/screenshot.zip)
- [Chrome.extensions.tabs.captureVisibleTab API](https://developer.chrome.com/extensions/tabs#method-captureVisibleTab)
- [一篇网上找到的参考文章](http://louisrli.github.io/blog/2013/01/16/javascript-canvas-screenshot)

**Comment by kaid** [comment]
实现了一个demo插件https://github.com/kaid/chromium-ext-screenshot-demo/
下载地址https://github.com/kaid/chromium-ext-screenshot-demo/releases

安装方法: chrome浏览器打开开发模式，将下载后的插件拖拽入chrome窗口

**Comment by ben7th** [comment]
基础逻辑已经开发完毕。后续可进一步改进插件体验。
