### ISSUE TITLE
在收藏网址到四叶书签时, 希望把近期使用过的书签 TAG 列出来

### ISSUE THREAD

**Issue by pimgeek** [mindpin/problems#35]
我经常会一次收藏一系列网址, 这些网址通常都是某一个具体的人推荐的, 或者来自某一个具体的网站. 比如 [sina-blog], [zhihu-user1], ...

但是, 我每次点 【四叶书签】收藏按钮时，都必须重新输入一次相同的 TAG。

这就是我面临的问题，我的目的是减少相同 TAG 的重复输入。

**Comment by ben7th** [comment]
给已经做好的东西提 issue 去另一个地方提：

https://github.com/mindpin/problem-issues/issues?state=open

这样有利于我们把原始问题和改进建议分开处理。
