### ISSUE TITLE
对四叶书签的体验优化建议

### ISSUE THREAD

**Issue by pimgeek** [mindpin/problems#41]
@pimgeek 与 @ben7th 在闲聊中提到, 看到四叶书签的编辑界面, 隐约感觉到利用四叶书签收集到的数据, 完全可以很容易地展现为 Pinterest 瀑布流的形式. 但目前四叶书签的编辑界面并未给出这种视觉暗示. 

基于这个上下文, 我希望有这样一种体验优化:

在弹出书签编辑界面之后, 能够有一个视觉提示, 通过视觉提示告诉我通过四叶书签输入的数据, 能够直接展现为哪些常见的策展形式. 比如 Pinterest, Facebook Timeline, 动态多尺寸矩形填充.... 等. 

以下图片仅供参考, 主要为了表达目的, 而不是强调实现手段.
![image](https://cloud.githubusercontent.com/assets/1609306/3011064/204de4d8-df24-11e3-9da2-759ef75974c6.png)

这里所谓的视觉提示, 是指类似于 http://jobs.4ye.me 里作品展示那样的视觉提示.

![image](https://cloud.githubusercontent.com/assets/1609306/3011035/80aa3404-df23-11e3-97a8-32a3f9ef975a.png)

**Comment by advancer-zz** [comment]
建议，优化时，尽量收敛到具体的问题或场景上，以增加可操作性与实用性

**Comment by pimgeek** [comment]
此 issue 本来应该被放置在 problem-issue 位置. 我提错位置了.
https://github.com/mindpin/problem-issues/issues/18
