### ISSUE TITLE
需要一个在线制作和发布 [趣味调查问卷] 的小工具

### ISSUE THREAD

**Issue by pimgeek** [mindpin/problems#45]
#### 使用场景说明

使用场景仅仅被用来衬托 persona, 后面的需求说明才是开发依据.

**小强(persona)** 在乘公交车上班路上, 试着刷微信朋友圈, 发现有位朋友转发了一段趣味测试, 目测只要简单地操作几个步骤, 就能判断出自己属于那种牛人类型: 工程师型, 科学家型, 哲学家型, 艺术家型, 历史学家型...
#### 需求说明

1 使用者可以在桌面浏览器或者 Android 浏览器(含微博/微信内置浏览器)中的运行这个问卷.
2 问卷编辑工具支持的提问方式至少有一种, 单选题.
3 在线编辑问卷题目的工具功能点集合, 只要能够覆盖 4ye 草学习助手编辑器的功能点即可.
4 当使用者运行问卷的时候, 每做完一道题目, 都会得到一定的分值.
**5 使用者完成一轮测试之后会形成一个分值序列, 问卷工具将根据分值序列映射到某种结果类型.**

> 4, 5 两项相关说明: 每道题的得分规则, 以及从分值序列到结果类型的映射关系, 由 @pimgeek 给出

**Comment by ben7th** [comment]
文艺大师直接叫艺术家就好了

**Comment by pimgeek** [comment]
已经修改

**Comment by ben7th** [comment]
你是需要这样一个工具？
那这样，我们先思考：目前如果不做任何开发，你手头有的，你靠搭或者攒，能够实现这个需求的途径是什么

**Comment by ben7th** [comment]
我会尝试用这种方式提炼需求：
1. 先考虑如果不做任何开发，用现有条件如何做，哪怕这个方式很费劲；
2. 这个费劲的方式，重复10遍，重复100遍的话，哪里最让人头大
3. 如果以某种方式克服了这个头大的点，再回头想 1
4. 1-2-3 没得可想了，此时就可以确定应该如何使用技术资源了。

**Comment by ben7th** [comment]
关于 persona ，我想，可以把常用的 persona 做成类似这样的表格，便于复用

![image](https://cloud.githubusercontent.com/assets/322486/3156989/ea9c3622-eaeb-11e3-8c74-010934c7f09e.png)

**Comment by ben7th** [comment]
上面这张图来自这篇文章
http://www.36kr.com/p/212238.html

以Quora安卓客户端的重构为例，Norman Tran教你玩转Persona、Framework、Sketch和Prototype

有时间的话可以 read it later

**Comment by pimgeek** [comment]
如果不做任何开发, 我首先想到的是 http://wufoo.com , http://www.surveymonkey.com 这类在线调查问卷工具, 这类网站可以支持单选题, 插入图片, 答案日志查看, 答案以 csv 导出等.

经过简单的在线搜索, 我发现有一个在线调查问卷工具 **在功能上** 完全支持我的需求, 我利用它出了一个简单的示例: http://www.surveygizmo.com/s3/1681612/test 

实际在 Desktop 和 Android 浏览器中测试, 发现速度太慢, 无法忍受.

**Comment by pimgeek** [comment]
更进一步, 我试图在中文网站中搜索具有同样功能的网站, 尝试了一下 http://www.diaochapai.com 这个在线问卷调查网站. 我仍然是利用它创建了一个简单的示例:

http://www.diaochapai.com/survey911854

这个网站的速度明显快过国外网站, 在手机上访问时底部会出现广告, 但这在目前的目的而言并不妨碍我达到目的. 所以, 目前此 issue 可以 close

**Comment by ben7th** [comment]
你先试试用 diaochapai 多尝试几次你要做的实验，如果重复过程中发现一些痛点，我们再研究如何使用开发资源解决。

**Comment by ben7th** [comment]
引用 https://github.com/mindpin/problems/issues/47
