### ISSUE TITLE
需要对 code.org 网站做一些相关调研

### ISSUE THREAD

**Issue by pimgeek** [mindpin/problems#61]
@ben7th 在 2014-10-09 提出需求【需要对 code.org 网站做一些相关调研】

现在给出调研结果。

1 这个网站主要的教学内容是什么？基本都是编程，还是包括更多领域？或者说（因为域名所限）如果都是围绕计算机类课程的话，有没有类似“计算机文化”这种非操作类的，比较务虚的课。
- 仔细浏览了几遍，教学内容主要是【编程基础知识的讲解】，【编程操作练习】，以及【不用电脑的活动】这三类内容。
- 内容的知识范围主要都在编程/算法领域，不涉及其它领域的知识。
- 大部分编程课程都包含了一定的拖拽式编程操作练习和算法相关练习等，没有“计算机文化”这类务虚的课程。

2 这个网站的教学内容以什么形式呈现？主要的形式是视频，还是可操作的互动场景？（这里“主要的”指从数量上而言更多的，而不是指给你印象更深的。）给你印象比较深的是其中的什么课？为什么给你印象很深？
- 网站的教学内容主要以三种形式出现：【视频/图文讲解】形式，【Blockly 拖拽式编程积木操作】形式（可操作的互动场景），【单项选择题】形式（非常类似于智商测试）
- 相对数量最多的教学内容是 Blockly 拖拽式编程积木操作，其次是与算法相关的选择题，视频讲解相对最少。
- 给我印象比较深的是【迷宫】和【Artist】这两个课程，它们看似简单，但却能有效矫正物体在平面上位移的方向和角度等直觉，另外给我印象比较深的一点是，用 Blockly 编程积木的方式编写过程代码，更有利于把思维集中在【希望通过编程解决的主要问题】上面。

3 这个网站的教学视频呈现方面有什么特点？或者换句话说，围绕视频组织，他做了什么独特的创意吗？
- 围绕视频组织的创意并无独特创意。但在【迷宫】课程中，伴随教学视频，还提供了视频截图+文字说明的可选浏览方式，其载入速度明显更快。因为我急于了解视频讲解要点，所以这个浏览方式有一定帮助。

4 这个网站的互动场景有什么特点？和其他类似网站（或者和我们做的js-warrior）相比，有什么做得更好的，值得参考的地方？
- 这个网站的互动场景特点有许多：
  - 每个模块都如同拼图块那样，有凹凸不平的区域，给人可拼装的直观感觉。
  - 拖拽模块即可组装，只有少数情况需要输入参数，这减少了逐个字母敲入代码时容易出现的拼写错误。
  - 随时都可以显示已组装模块背后的实际代码，方便初学者在头脑中建立模块与实际的代码之间的联系。
- 与 js-warrior 相比
  - 从总体上看，【迷宫】的可调用模块远远比 js-warrior 简单，更适合初学编程的人。而 js-warrior 的变数和挑战性更强，适合解谜型游戏爱好者。
  - 体验过【迷宫】的互动过程之后，我对 loop，do..until 这两个模块印象深刻，前者减少了我重复拖拽同类模块的动作，后者则消除了考虑循环次数的麻烦。
  - 用模块的拖拽代替手工输入函数调用，更加直观易懂，让新手的心理压力降低，也减少了键盘输入出错的可能性。
  - 模块以凹凸拼图块的形式展现，对初学者产生更多视觉暗示，更容易自动把握操作要领。
  - 只暴露与任务相关的模块，让新手的心理压力降低。

5 这个网站的所有课程章节组织有什么特点？是否基于同样的章节组织结构？还是说每个课程的内容都是根据本课程组织的，没有明显的统一的章节组织形式？
- 这个网站的所有课程章节组织并没有明显的特点。分为【课程】【章节】和【小节】三个级别，在部分【章节】的开头标出了不用电脑的活动。学习过并且完成了任务的【小节】以对勾图标展示，否则以数字序号展示。【章节】则始终以标题方式展示。
- 各个课程基于同样的章节组织结构。

6 这个网站能让哪些角色（学生，老师，其他）参与其中？每种角色如何参与？
- 网站让三种角色参与，学生，老师和贡献者
- 学生可以学习课程内容并进行练习，即使不登录也可以学习与练习，只有登录后才保存练习进度。登录后，还可以加入教师用户创建的教学节点。
- 老师登录后，既可以学生身份参与学习和练习，也可以教师身份创建教学节点，并且招收学生加入这个教学节点。一个教学节点只能管理一个课程，但可以招收多个学生。学生加入后，教师可以看到每个学生的学习进度等信息。教师还可以利用简单的管理界面完成【修改学生的账号密码】，【从教学节点中移除学生】等操作。除了基本的在线教学任务，教师还可以访问网站上提供的各类教育资源，包括一小时编程计划，K-5/K-8 计划，使用 Bill Gates，Mark Zackerberg，Obama 等人出镜的【编程教学推广视频】等。
- 贡献者参与的方式主要是捐款。

7 虽然是 org 网站，但这个网站是否有盈利倾向？如果有的话，形式可能是什么？还是完全公益的？
- 从 TechCrunch 旗下的 CrunchBase 调查得知：此网站是完全非盈利的，致力于计算机编程教育的发展。包括向队伍传播【全世界的程序员都存在短缺】【学程序并没有想象得那么难】等信息；建立编程学校的权威数据库，无论它们是在线学校，传统实体学校还是夏令营。此组织主要针对美国，力求把编程教育放进美国 STEM(Science Technology Engineering Mathematics) 教育的核心课程中。
- 参考链接 - http://www.crunchbase.com/organization/code-org
- 创始人信息(翻墙访问) - http://visual.ly/vizbox/startup-universe/show/vc/ali-partovi

**Comment by ben7th** [comment]
后续讨论中提出的一些点：
1. 务虚和务实的定义：宋亮的定义是能跟着动手，且老师能感知到这个动手过程的是务实，其他的算务虚。务虚和务实只是分类，和“有用”“没用”没有直接关系。
2. 希望编程教学场景能够尽快让学习者感受到在程序的作用下，计算机做出了“超越”人类的简单决策能力的事情，而不仅仅是重复指令
3. 宋亮了解了 Blockly 积木式拖拽变成场景之后，提出两点微创新方向：一是将其美术风格修改成更潮流化；二是这个拼图的文化隐喻（凹凸拼图）比较西方化，希望能找到更东方化的文化隐喻
4. 互动编程的代码检查过程可以更加自动化。减少用户操作数（如 j s k网站）
5. 视频方面，提出也许可以用 facerig 这样的卡通虚拟形象取代真人形象教学，以减低学生压力和提升趣味性
6. 对于PGC网站，可以借鉴 code.org 的课程节点的思路，让更多的老师参与进来
