### ISSUE TITLE
需要一个特性：粘贴图片到 img.4ye.me 之后，直接给出【多种尺寸选择】的超链接

### ISSUE THREAD

**Issue by pimgeek** [mindpin/problems#65]
这是我粘贴完图片后，希望有的入口超链接 - http://img.4ye.me/images/dx5w8by0 （我称之为【多种尺寸选择】的入口）

![](http://img.teamkn.com/i/dx5w8by0.png)

实际上我得到的却是单张图片的超链接 - http://img.teamkn.com/i/dx5w8by0.png

**Comment by ben7th** [comment]
已经修改。现在点击指定位置会跳到详情页。
