### ISSUE TITLE
我需要一种图片转贴+存储工具

### ISSUE THREAD

**Issue by pimgeek** [mindpin/problems#7]
我以前在几个不同网站上发布过图文帖子(html格式)，当我需要把帖子手工粘贴到某个在线编辑器时，显然文字部分可以直接复制粘贴到在线编辑器中，但是图片不能。

现在我很需要一种图片转贴+存储工具:

1 图片可以随着图文内容一起粘贴到编辑器中
2 图片被自动保存到某个云端存储位置

如果存在这样的在线编辑器 我会很乐意经常往这个编辑器里丢图文内容 不然我会觉得压力太大

**Comment by ben7th** [comment]
准备开发图片粘贴上传web服务。

不过有以下几个约束：
1. 需要用chrome浏览器来访问。
2. 只能单独粘贴图片和粘贴文字，可能不能同时粘贴图文混排内容。
3. 先不提供富文本格式控制。

**Comment by pimgeek** [comment]
OK，做出来我会立刻试用。

**Comment by ben7th** [comment]
img.4ye.me 首页现在可以支持 ctrl + V 来粘贴图片数据

建议使用方法：
用QQ截图工具框选要截的区域，点勾之后图片数据会进入剪贴板（千万不要从QQ里点右键复制图片，那样出来的数据不是合理的数据）
然后在 img.4ye.me 首页 ctrl + V 就可以触发图片的上传了
