### ISSUE TITLE
我需要一种可以对 [应聘者简历邮件] 内容做解析的工具

### ISSUE THREAD

**Issue by pimgeek** [mindpin/problems#9]
### 使用场景说明

问题的场景是这样的，我在互联网上发出了招聘信息之后，会收到来自各个招聘网站（比如【58 同城招聘专区】，又比如【周伯通招聘网】）发来的【应聘简历】邮件。
#### 待处理的内容

简历邮件的内容大概如下图所示

![image](https://f.cloud.github.com/assets/1609306/2508719/8509181c-b3e0-11e3-8411-629c206bf4ec.png)
#### 预期的输出

从图中的标记可以知道，我最关心的三项信息是：

1 应聘者的姓名
2 TA 是从哪个招聘网站来的
3 TA 投递简历的时间究竟是哪一天
#### 这样输出的目的

我之所以关注这些信息，是因为我要把它们手动填写到下面这张电子表格里。

> ![image](https://f.cloud.github.com/assets/1609306/2509375/2db2a1f8-b3f1-11e3-8413-9f97d37688bc.png)

---
### 期待的具体工具及具体功能详述

有了上面的场景铺垫，我就可以说出我需要怎样的解析工具：
#### 关键输入

我把任何一个简历邮件转发给 cv-helper@mindpin.com 
#### 关键处理过程

邮件账号会收到简历邮件，并且解析邮件正文，把简历邮件中所有的【关键信息片段】都提取出来。
#### 人工处理过程

这样提取出来以后，不可能准确，但我可以接受一种变通的点选方式：

**用鼠标点击所需的【信息片段】，点击后会自动填充到空格里。**

> **简历填空模板**：简历来自应聘者 ____ ，这份简历是在 ___ 这一天，从招聘网站 ____ 发来的。
> **信息片段列表**: (请点选任何一个片段，以便填空)
> [Android 开发工程师 (来自周伯通招聘)], [周伯通招聘], [3月25日], 
> [mindpin], [Android 开发工程师 - XX], [Android 开发工程师], 
> [无], [XX], [男], 
> [20], [xxxx@qq.com], [13xxxxxxxx],
> [目前在职，考虑换个环境]
> **邮件全文**: [.... 完整显示邮件全文，便于肉眼参照]

**我预想中的自动填空的 UI 类似于四叶草知识手册**
- **答题填空模板** ==> **"简历填空模板"**
- **答题选项** ==> **信息片段**
- **答题操作** ==> **点选信息片段的操作**

> ![image](https://f.cloud.github.com/assets/1609306/2509602/2aa5e26c-b3f7-11e3-9f5b-c7753df7d5f0.png)
#### 最终的输出

允许我以 csv 格式导出一行或多行数据：例如:

"XX", "周伯通招聘", "2014-03-21"
"XXX", "58同城", "2014-03-17"

**Comment by ben7th** [comment]
目前看来主要是用来在网页上采取信息，因此也考虑开发浏览器插件来满足要求。
先放入执行队列了。

最新执行队列情况：
http://s.4ye.me/ttuFmH

**Comment by ben7th** [comment]
请先把要采集的字段逐一告诉我。

**Comment by pimgeek** [comment]
我目前只需要三个字段:
申请者姓名, 简历来源, 申请日期
对应的英文是
applicant_name, cv_source, application_date

**Comment by pimgeek** [comment]
提需求的误区: 没有抽取出最关键的核心信息流, 反而用自己的 [直观解决方案] 干扰了开发者思考.

**Comment by ben7th** [comment]
problem 提出的时候附带了很具体的解决方法，开发人员不太容易提取出本源问题。建议可以去掉解决方法之后，把本源问题和希望得到的输出重新提出。

**Comment by advancer-zz** [comment]
是啊，需要强调“问题或需求本身”，将场景、输入与输出的具体特征描述清楚。若将关注点放在实现形式上，由于不同的人对于实现形式的理解存在相当大的差异，可能就会不容易收敛，不仅带来很多沟通成本，而且可能做出来后，由于对需求反省与提炼不足，造成“绣花枕头”，缺乏操作上的可行性.
